# training
NUM_EPOCH: 100
TRAIN_BATCH_SIZE: 4
TEST_BATCH_SIZE: 1
LR: 0.05
LOSS: 'CE'
BACKBONE: 'resnet'
  # - 'mobilenet'
  # - 'drn'
  # - 'xception'

# results
RESULT_DIR: './results'
SAVE_MODEL_DIR: './saves'

# else
DEBUG_MODE: False